server:
  servlet:
    context-path: /cliente-pet/api

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger

spring:
  datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /console